language: python

python:
  - "pypy3"
  - "3.3"
  - "3.4"
  - "3.5"

install:
    - pip install pytest
    - pip install pytest-cov
    - pip install codecov
    - pip install .

script:
    - py.test --cov=$(cd tests&&python -c "import validr;print(validr.__path__[0])")

after_success:
    - codecov
