language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
    - pip install pytest
    - pip install pytest-cov
    - pip install flake8
    - pip install codecov
    - pip install cython
    - python setup.py sdist
    - pip install --ignore-installed dist/validr-*.tar.gz
    - pip uninstall -y cython
    - pip install --ignore-installed dist/validr-*.tar.gz

script:
    - export VALIDR_PATH=$(cd /tmp && python -c "print(__import__('validr').__path__[0])")
    - pytest --cov=$VALIDR_PATH --cov-report=term-missing
    - flake8
    - pip install -r requires-dev.txt
    - python benchmark/benchmark.py benchmark

after_success:
    - codecov
