language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"

install:
    - pip install -U pip
    - pip install -U py  # work around pytest requirement
    - pip install -r requires-dev.txt
    - pip install -r requires-benchmark.txt

script:
    - pre-commit run --all-files
    # develop install
    - cd $TRAVIS_BUILD_DIR
    - VALIDR_USE_CYTHON=1 VALIDR_DEBUG=1 pip install --ignore-installed -e .
    - pytest --cov=validr --cov-report=term-missing tests

    - VALIDR_USE_CYTHON=1 python setup.py sdist
    # normal install
    - cd $TRAVIS_BUILD_DIR
    - pip install --ignore-installed dist/validr-*.tar.gz
    - cd /tmp && pytest $TRAVIS_BUILD_DIR/tests
    - cd /tmp && python $TRAVIS_BUILD_DIR/benchmark/benchmark.py benchmark

after_success:
    - codecov
