language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

env:
  - VALIDR_DEBUG=0
  - VALIDR_DEBUG=1

install:
    - pip install -U pip
    - pip install -U py  # work around pytest requirement
    - pip install -r requires-dev.txt
    - pip install -r requires-benchmark.txt

script:
    - pre-commit run --all-files
    - VALIDR_USE_CYTHON=1 python setup.py sdist
    # normal install
    - pip install --ignore-installed --verbose dist/validr-*.tar.gz
    - cd /tmp && pytest tests

    # install using cython to compile *.pyx
    - VALIDR_USE_CYTHON=1 pip install --ignore-installed --verbose dist/validr-*.tar.gz
    - cd /tmp && pytest tests

    # develop install
    - cd $TRAVIS_BUILD_DIR
    - pip install --ignore-installed -e .
    - pytest --cov=validr --cov-report=term-missing tests
    - python benchmark/benchmark.py benchmark

after_success:
    - codecov
