language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"

matrix:
    allow_failures:
        - python: "pypy3"
        - python: "nightly"

install:
    - ./bootstrap.sh

script:
    - pre-commit run --all-files
    # develop install
    - cd $TRAVIS_BUILD_DIR
    - inv build --debug
    - pytest --cov=validr --cov-report=term-missing tests
    # normal install
    - inv build
    - cd $TRAVIS_BUILD_DIR
    - pip install --ignore-installed dist/validr-*.tar.gz
    - cd /tmp && pytest $TRAVIS_BUILD_DIR/tests
    - cd /tmp && python $TRAVIS_BUILD_DIR/benchmark/benchmark.py benchmark

after_success:
    - codecov
