language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

env:
  - VALIDR_DEBUG=0
  - VALIDR_DEBUG=1

install:
    - pip install -U pip
    - pip install -U py  # work around pytest requirement
    - pip install -r requires-dev.txt

script:
    - pre-commit run --all-files
    - python setup.py sdist
    - pip install --ignore-installed --verbose dist/validr-*.tar.gz
    - export VALIDR_PATH=$(cd /tmp && python -c "print(__import__('validr').__path__[0])")
    - pytest --cov=$VALIDR_PATH --cov-report=term-missing -r w
    - pip uninstall -y cython  # test install without cython
    - pip install --ignore-installed --verbose dist/validr-*.tar.gz
    - export VALIDR_PATH=$(cd /tmp && python -c "print(__import__('validr').__path__[0])")
    - pytest --cov=$VALIDR_PATH --cov-report=term-missing -r w
    - pip install cython  # cython is need for coverage
    - pip install --ignore-installed --verbose -e .
    - pytest --cov=validr --cov-report=term-missing -r w
    - python benchmark/benchmark.py benchmark
    - python benchmark/benchmark.py profile

after_success:
    - codecov
